# Generated by Django 3.2 on 2023-08-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DANHMUCSANPHAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmspTen', models.CharField(max_length=256, null=True)),
                ('dmspDuongdan', models.SlugField(blank=True, max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOAISANPHAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lspTen', models.CharField(max_length=256, null=True)),
                ('lspDuongdan', models.SlugField(blank=True, max_length=256, null=True, unique=True)),
                ('dmsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.danhmucsanpham')),
            ],
        ),
        migrations.CreateModel(
            name='SANPHAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spTen', models.CharField(max_length=256, null=True)),
                ('spGioiThieu', models.TextField()),
                ('spCongdung', models.TextField()),
                ('spHuongdansudung', models.TextField()),
                ('spThanhphan', models.TextField()),
                ('spDongia', models.IntegerField()),
                ('spHinhanh', models.ImageField(upload_to='product')),
                ('lsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.loaisanpham')),
            ],
        ),
    ]
