# Generated by Django 3.2 on 2023-08-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230824_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='spDuongdan',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
