# Generated by Django 3.2 on 2023-09-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230912_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='khPhone',
            field=models.CharField(max_length=12),
        ),
    ]
