# Generated by Django 3.2 on 2023-09-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_khachhang_khphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaisanpham',
            name='lspThumb',
            field=models.ImageField(default=2317, upload_to='product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DONDATHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddhNgay', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='CT_DONDATHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(blank=True, default=0, null=True)),
                ('NgayThem', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dondathang')),
                ('sanpham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sanpham')),
            ],
        ),
    ]
