# Generated by Django 3.2 on 2023-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230918_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ct_dondathang',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='dondathang',
            options={'verbose_name': 'Đơn đặt hàng', 'verbose_name_plural': 'Đơn đặt hàng'},
        ),
        migrations.AlterField(
            model_name='ct_dondathang',
            name='NgayThem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
