# Generated by Django 3.2 on 2023-09-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230923_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dondathang',
            old_name='user',
            new_name='customer',
        ),
    ]
