# Generated by Django 3.2 on 2023-09-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_user_dondathang_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dondathang',
            old_name='customer',
            new_name='user',
        ),
    ]
