# Generated by Django 3.2 on 2023-09-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_khachhang_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dondathang',
            name='user',
        ),
        migrations.DeleteModel(
            name='CT_DONDATHANG',
        ),
        migrations.DeleteModel(
            name='DONDATHANG',
        ),
    ]
