# Generated by Django 3.2 on 2023-09-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='sanpham',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='soluong',
            new_name='quantity',
        ),
    ]
