# Generated by Django 3.2 on 2023-10-05 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_auto_20230925_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Đã xác nhận'), ('Packed', 'Đóng gói'), ('On the way', 'Đang giao hàng'), ('Delivered', 'Đã giao hàng'), ('Cancel', 'Hủy'), ('Pending', 'Đang xử lý')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.khachhang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sanpham')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
