# Generated by Django 3.2 on 2023-11-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_auto_20231008_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAIVIET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baivietTen', models.CharField(max_length=255)),
                ('bvNoidung', tinymce.models.HTMLField()),
                ('bvNgaytao', models.DateTimeField(auto_now_add=True)),
                ('bvDuongdan', models.SlugField(blank=True, max_length=256, null=True, unique=True)),
                ('bvThumb', models.ImageField(upload_to='thumb')),
                ('bvTrangthai', models.CharField(choices=[('bản nháp', 'Bản nháp'), ('hiển thị', 'Hiển thị')], default='Bản nháp', max_length=255)),
                ('bvTacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
            },
        ),
        migrations.CreateModel(
            name='CTLONHAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongNhap', models.PositiveIntegerField(default=1)),
                ('giaNhap', models.IntegerField()),
                ('ngaysanxuat', models.DateField()),
                ('hansudung', models.DateField()),
            ],
            options={
                'verbose_name': 'Thông tin lô nhập',
                'verbose_name_plural': 'Thông tin lô nhập',
            },
        ),
        migrations.CreateModel(
            name='LOAIBAIVIET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaibaivietTen', models.CharField(max_length=20)),
                ('lbvDuongdan', models.SlugField(blank=True, max_length=256, null=True, unique=True)),
                ('lbvHinhanh', models.ImageField(upload_to='thumb')),
            ],
            options={
                'verbose_name': 'Loại bài viết',
                'verbose_name_plural': 'Loại bài viết',
            },
        ),
        migrations.CreateModel(
            name='LONHHAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayNhap', models.DateField()),
            ],
            options={
                'verbose_name': 'Lô nhập',
                'verbose_name_plural': 'Lô nhập',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nccTen', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.AddField(
            model_name='lonhhap',
            name='ncc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
        migrations.AddField(
            model_name='ctlonhap',
            name='loNhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.lonhhap'),
        ),
        migrations.AddField(
            model_name='ctlonhap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sanpham'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='loaibaiviet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.loaibaiviet'),
        ),
    ]
